### ISSUE TITLE
Block-commented code is unindented on prettyprint

### ISSUE THREAD

**Issue by ottworks** [FPtje/linter-glualint#10]
![](http://i.imgur.com/ew5IrZC.png)

**Comment by FPtje** [comment]
I run `selection.autoIndentSelectedRows()` over the pretty printed code in atom. For some reason that function decides that everything in comments must have preceding whitespace removed. Perhaps @Lixquid, author of [the GMod Lua plugin](https://github.com/Lixquid/atom-language-gmod-lua) can help it.

**Comment by Lixquid** [comment]
Just to chime in, this is sort-of intended behaviour. Atom suppresses grammar rules when inside a comment, based on the assumption that inside a comment will be natural English. Natural English has no indentation rules, so all indentation is stripped.

If this is an issue, you can iterate over all lines, check if they're a comment by calling `TextEditor.isBufferRowCommented`, and if `false` is returned, run `TextEditor.autoIndentBufferRow` on the row.

@FPtje @0tt

**Comment by FPtje** [comment]
That could be a dangerous assumption. "real" comments can contain code examples, but also tables to visualise something, or maybe some indented hierarchy.

**Comment by Lixquid** [comment]
Sorry, maybe I was unclear; it's not the grammar file itself that makes the assumption, but Atom's language system. Comments have no indentation regardless of the grammar selected.
