### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by yobson1** [FPtje/linter-glualint#14]
Everything was working up until I returned to do some glua stuff. Haven't touched it in a few months and now suddenly the linting isn't working. I'm not really sure what info I can supply you with as I haven't made any changes to the lua or linting packages of atom here is what I can confirm:

Linter is installed and works, just not with this provider
Glualint is installed to path correctly: https://i.imgur.com/AspAjgr.png
Glaulint will give a proper response if I give it a file from cmd: https://i.imgur.com/19RqwOP.png

What I have already tried:
Re-installing the atom package
Updating the glualint executable
Re-installing the linter package
Disabling all other packages other than linter and glualint
Entering the path of the executable in the glualint package settings

Despite this it does not show the linting within atom at all as it did last time I used it. If there is some steps I can take to help debug this let me know and I will do what I can.

**Comment by FPtje** [comment]
Looks like the Atom Linter developers made some breaking updates to their linter, breaking older linters in the process. Looks like I'm gonna have to recode a bunch. Might take a while.

Some references for myself:
https://steelbrain.me/linter/
https://github.com/AtomLinter/atomlinter.github.io#adding-a-linter-provider

**Comment by yobson1** [comment]
Appreciate the quick response. Can confirm going back to linter version 2.2.0 fixes the issue. I'll just use that for now, thanks.

For anyone else who stumbles onto this wondering how to do the same just uninstall linter and then run "apm install linter@2.2.0" at cli

**Comment by FPtje** [comment]
Awesome. Turns out switching to the latest linter isn't too bad. I've pushed a commit that should make it compatible. I haven't made a release yet, because I've got to figure out how that works again. Also, I have to look into adding a linter provider (as linked above). 

I'll keep this issue open to work on that later.

**Comment by FPtje** [comment]
Alright, the update has been published, and a PR has been made to add it to the providers list. Thanks for reporting the issue!
