### ISSUE TITLE
Linter only on save

### ISSUE THREAD

**Issue by ghost** [FPtje/linter-glualint#15]
Hello, i'm having a issue where the lintener appears once i'm saving my file and not while i'm typing whereas the "Lint on Save" parameter is disabled...

So can you help me please ?

**Comment by FPtje** [comment]
The glualint package forced linting by file. Now it uses linting through stdin. Note that you need to upgrade glualint for it to see the project's `glualint.json` properly. See https://github.com/FPtje/GLuaFixer/issues/57
