### ISSUE TITLE
Disable for project

### ISSUE THREAD

**Issue by looterz** [FPtje/linter-glualint#3]
It would be great if I could easily disable or enable glualint for particular projects. Dealing with legacy code is a must sometimes, and id rather not have to rewrite entire non-conforming projects just to get half my workspace window back.

**Comment by looterz** [comment]
Woops, wrong project.

**Comment by FPtje** [comment]
This is simply solved by grabbing the config file, setting everything to false and 0 and then putting it at the root of the project.

**Comment by looterz** [comment]
Sounds like a good solution to me, thanks.
