### ISSUE TITLE
Weird Glitch

### ISSUE THREAD

**Issue by dan2735** [FPtje/linter-glualint#8]
`if not ply:Team() ~= TEAM_TOWER then return end`

When I have that it says:
Silly negation. Use '=='at line 163 col 19

`if not ply:Team() ==TEAM_TOWER then return end`

When I have that it says:
Silly negation. Use '=~'at line 163 col 19

Which do I believe!

**Comment by FPtje** [comment]
The error message is correct. This:

``` lua
if not ply:Team() == TEAM_TOWER then return end
```

Should be turned into this:

``` lua
if ply:Team() ~= TEAM_TOWER then return end
```

basically, `not (a == b)` should be `a ~= b`, and `not (a ~= b)` should be `a == b`.
